name: ESLint check and deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  lintvalidationanddeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ESLint
        run: |
          npm install eslint eslint-plugin-html --save-dev
          npx eslint .

      - name: Deploy to Firebase Hosting
        if: success()
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FB_CLONE_FAD57 }}
          channelId: live
          projectId: fb-clone-fad57
