name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  lint_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ESLint
        run: npm install -g eslint

      - name: Run ESLint
        run: eslint . --ext .html,.css
        # Run ESLint on HTML and CSS files. Adjust the file extensions if needed.

      - name: Deploy to Firebase Hosting
        if: success() # Only deploy if ESLint passed
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FB_CLONE_FAD57 }}
          channelId: live
          projectId: fb-clone-fad57


