name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  lint_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint
        # This step runs ESLint. Adjust the command according to your project setup.
        # If ESLint fails, the workflow will stop here.

      - name: Deploy to Firebase Hosting
        if: success() # Only deploy if ESLint passed
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FB_CLONE_FAD57 }}
          channelId: live
          projectId: fb-clone-fad57

