name: ESLint check and deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  lint-validation-and-deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Add any necessary setup steps here, such as installing dependencies

      - name: validate-license-action
        uses: datreeio/validate-license-action@v1.0.0
          
      - name: Archive Production Build
        uses: actions/upload-artifact@v4.3.1

  Deploy-to-production:
    runs-on: ubuntu-latest
    environment:
      name: Prod  # Fixing the typo here
    steps:
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FB_CLONE_FAD57 }}
          channelId: live
          projectId: fb-clone-fad57
