name: ESLint check and deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  lint-validation-and-deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        

  Deploy-to-production:
    runs-on: ubuntu-latest
    needs: lint-validation-and-deploy
    if: success()
    environment:
      name: Prod
    steps:
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FB_CLONE_FAD57 }}
          channelId: live
          projectId: fb-clone-fad57
