name: ESLint check and deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main
jobs:
  lint-validation-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: Prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Add any necessary setup steps here, such as installing dependencies

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FB_CLONE_FAD57 }}
          channelId: live
          projectId: fb-clone-fad57
